name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PEM key
        env:
          EC2_KEY_BASE64: ${{ secrets.EC2_KEY_BASE64 }}
        run: |
          # Decode the base64-encoded private key and save it as ec2_key.pem
          echo "$EC2_KEY_BASE64" | base64 --decode > ec2_key.pem
          # Set appropriate permissions for the key file
          chmod 600 ec2_key.pem

      - name: SSH into EC2 and Deploy
        env:
          EC2_PUBLIC_IP: "34.204.74.69"  # Replace with your EC2 instance's public IP
        run: |
          # SSH and run deployment commands on the EC2 instance
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@$EC2_PUBLIC_IP \
            "cd /var/www/html && git pull origin main && sudo systemctl restart apache2"
